name: Bug
description: Ex. Sub-levels not rendering properly, or anything else that isn't a crash or feature request
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: mod-version
    attributes:
      label: "Mod Version"
      description: "What version of SSRD are you using?"
      placeholder: "e.g., v1.8"
    validations:
      required: true
  - type: input
    id: other-mod-version
    attributes:
      label: "Other mods being used"
      description: "What other mods are you using, and what versions?"
      placeholder: "e.g., Sodium 0.8.#, Distant Horizons 3.1.#"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Any information you find relevant, could be a log file or complete modlist"
      placeholder: "Describe the issue here..."
    validations:
      required: true
  - type: checkboxes
    id: forceload-confirmation
    attributes:
      label: "I can read"
      options:
        - label: "If sub-levels aren't rendering past the vanilla render distance, I did attempt to forceload them using /ssrd forceload"
          required: true
