name: Feature Request
description: Request a feature to be added to SSRD
title: "Request a Feature"
labels: ["feature request"]
body:
  
  - type: textarea
    id: description
    attributes:
      label: "Description of the request"
      description: "Please provide a clear and concise description of whatever it is you're requesting"
      placeholder: "cmon lets here it"
    validations:
      required: false
